language:
- node_js
node_js:
- '0.10'
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
script:
- npm test
after_success:
- npm run archive
deploy:
  provider: s3
  access_key_id: AKIAJSHXGEZAYHQF3PBQ
  secret_access_key:
    secure: ZzmM30d9spcMUlCByohvOg4zBpX6rbB8HDlPG0DoERdL9Ky8luAUJ7WHTk5hbnQtNR/uRXkIbkDpboU02hEngfjQVhc4ZXbCVDHhi3e8tL6xalWhzYvWLoQQ7DWQspPJHlXoPkFyDodg5Aksqg/Z2ERPeW+C/5jZHaLbSzjEnVmWi/D1IXTvLce8dV/cMCbxdTweuXIYllE6TNaOC0CIlrV1SXNCduf+w46bXovOPhit6bjXy+a6Sptjepv4f3lDbzC057un4KhJ+TgHt1hWh1Z5FOT2mr3zjgaZzvd/OXyjZLJLKjtbXTViecaB2KO7sheYs+sySQbSX8i6t0h0Ze3veCBdFRsu2SqYXbisAKdlM2CEBKgk8wr/spYn204PeubNceJOj+VdQJUlVfapwt1ZNUmh8kH+msL0/YYG7aCJ4b2kyUHkKf5zO9DY0Wqhe4VwcAOwav25hHw2bg39B5fvnuMK/0H1s7TplWnKZkcX+MyzVRFx4oVOvcyqyM52JUsJGV1Wg57/B9DKvBwP/7OPWKfG664iE0Fl1GtSzY8oA1YwNh9IShfsZNdeS2cdqbDCGZbMMbIqFAsKwK5xId/DrAKsKav0KCZ63NsdJAk81qK+ImCi87A2bNeK/bgxqVqKHQrQetOUp9/fLfE2fVr9r7MpzseaR0A9/O5emII=
  bucket: file-repositories
  local-dir: dist
  upload-dir: lambda/lambda-deploy-custom-resource-function
  acl: public_read
  skip_cleanup: true
  on:
    repo: k-kinzal/lambda-deploy-custom-resource-function
    branch: master
    tags: true
